# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68523cadc18f37a6cfec858423a556404c6e9d4f6e5fa16e15853a54749f94dd7618ca337e4642da8a7540e376e351ef6563679cce331e78b0eb2f4081fe6f4c

test:
  secret_key_base: dc4ee872d6847bd67b06b6cc6b5a12baa127421e23238fd3dbfc6f06d4b66151e74616396274eaacc887ad2895a1423e26c84d3ba196e1a263c4977eb21a5730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
