# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2ef4504018c1c3f7f1e8458b48b6d414616aeb9cfdfa4366a6978c26bbdf51b52e3eb5a07bac897f8bf67652167a9f18b1460ce749a6a7995c99d7f8db1b1b7

test:
  secret_key_base: 7eb653cbe1d81ec8db6f8f7cbc7cc7d9ecb2946e77ab833685ac5a782f234e8c46683e2810f5e37df66b4415066cf2ceb130c47f574256777284f308f97ce35a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
