# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a5910fd8df668aacc7f062253f7b975af096996908eb2dd6f1dde96ccc54f35d876b1d7da7cae71feb14219e635633334dcda0b47f7841a232ba3e4f9d885e4

test:
  secret_key_base: 4846dd53c7ed51623019fdadda4e08f5248f22f64b063f83f0a4decdd0683bdcb620a862901fb64106236ddea8c711c6b454c63b041ec1c769538575f0fd223c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
